import { Stamp } from '@/app/dashboard/page';

export const mockVouchers: Stamp[] = [
  {
    tokenid: '1',
    restaurantName: 'SUBWAY NYC',
    discount: '15% OFF',
    discountType: 'percentage',
    discountAmount: 15,
    validUntil: '2024-12-31',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample1',
    description: 'Valtokenid for all menu items',
    variant: 'subway',
  },
  {
    tokenid: '2',
    restaurantName: 'UBER RIDE',
    discount: '$5 OFF',
    discountType: 'percentage',
    discountAmount: 5.0,
    validUntil: '2024-11-15',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample2',
    description: 'Minimum order $25',
    variant: 'taxi',
  },
  {
    tokenid: '3',
    restaurantName: 'BUS PASS',
    discount: '$10 OFF',
    validUntil: '2024-12-20',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample3',
    description: 'Minimum order $30',
    discountType: 'fixed',
    discountAmount: 10.0,
    variant: 'manhattan',
  },
  {
    tokenid: '4',
    restaurantName: 'Sushi Spot',
    discount: 'Buy 1 Get 1',
    validUntil: '2025-10-30',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample4',
    description: 'Valtokenid for sushi rolls only',
    discountType: 'fixed',
    discountAmount: 18.99,
    variant: 'restaurant',
  },
  {
    tokenid: '5',
    restaurantName: 'NYC BAR',
    discount: '15% OFF',
    validUntil: '2024-12-25',
    status: 'used',
    ipfs: 'https://ipfs.io/ipfs/QmExample5',
    description: 'Valtokenid Tuesday-Thursday',
    discountType: 'percentage',
    discountAmount: 15,
    variant: 'bar',
  },
  {
    tokenid: '6',
    restaurantName: 'Coffee Corner',
    discount: '$3 OFF',
    validUntil: '2024-12-20',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample6',
    description: 'Valtokenid for beverages only',
    discountType: 'fixed',
    discountAmount: 3.0,
    variant: 'coffee',
  },
  {
    tokenid: '7',
    restaurantName: 'POD 39 HOTEL',
    discount: '10% OFF',
    validUntil: '2024-10-15',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample7',
    description: 'Halloween special - expired',
    discountType: 'percentage',
    discountAmount: 10.0,
    variant: 'hotel',
  },
  {
    tokenid: '8',
    restaurantName: 'Burger Barn',
    discount: '$8 OFF',
    validUntil: '2025-11-30',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample8',
    description: 'Black Frtokeniday deal - already used',
    discountType: 'fixed',
    discountAmount: 8.0,
    variant: 'restaurant',
  },
  {
    tokenid: '9',
    restaurantName: 'Steakhouse NYC',
    discount: '30% OFF',
    validUntil: '2024-09-15',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample9',
    description: 'Summer special - expired',
    discountType: 'percentage',
    discountAmount: 30,
    variant: 'restaurant',
  },
  {
    tokenid: '10',
    restaurantName: 'Brooklyn Deli',
    discount: '$12 OFF',
    validUntil: '2024-11-20',
    status: 'used',
    ipfs: 'https://ipfs.io/ipfs/QmExample10',
    description: 'Thanksgiving special - used',
    discountType: 'fixed',
    discountAmount: 12.0,
    variant: 'restaurant',
  },
  {
    tokenid: '11',
    restaurantName: 'LEGO STORE',
    discount: '$5 OFF',
    validUntil: '2024-12-25',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample11',
    description: 'Valtokenid for pizzas only',
    discountType: 'fixed',
    discountAmount: 5,
    variant: 'luxury',
  },
  {
    tokenid: '12',
    restaurantName: 'Pizza Palace',
    discount: '$7 OFF',
    validUntil: '2025-12-18',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample12',
    description: 'Weekend special',
    discountType: 'fixed',
    discountAmount: 7.0,
    variant: 'restaurant',
  },
];
