import { Stamp } from '@/app/dashboard/page';

export const mockVouchers: Stamp[] = [
  {
    stampId: '1',
    storeName: 'SUBWAY NYC',
    discount: '15% OFF',
    discountType: 'percentage',
    discountAmount: 15,
    validUntil: '2024-12-31',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample1',
    description: 'Valtokenid for all menu items',
    variant: 'subway',
  },
  {
    stampId: '2',
    storeName: 'UBER RIDE',
    discount: '$5 OFF',
    discountType: 'percentage',
    discountAmount: 5.0,
    validUntil: '2024-11-15',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample2',
    description: 'Minimum order $25',
    variant: 'taxi',
  },
  {
    stampId: '3',
    storeName: 'BUS PASS',
    discount: '$10 OFF',
    validUntil: '2024-12-20',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample3',
    description: 'Minimum order $30',
    discountType: 'fixed',
    discountAmount: 10.0,
    variant: 'manhattan',
  },
  {
    stampId: '4',
    storeName: 'Sushi Spot',
    discount: 'Buy 1 Get 1',
    validUntil: '2025-10-30',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample4',
    description: 'Valtokenid for sushi rolls only',
    discountType: 'fixed',
    discountAmount: 18.99,
    variant: 'restaurant',
  },
  {
    stampId: '5',
    storeName: 'NYC BAR',
    discount: '15% OFF',
    validUntil: '2024-12-25',
    status: 'used',
    ipfs: 'https://ipfs.io/ipfs/QmExample5',
    description: 'Valtokenid Tuesday-Thursday',
    discountType: 'percentage',
    discountAmount: 15,
    variant: 'bar',
  },
  {
    stampId: '6',
    storeName: 'Coffee Corner',
    discount: '$3 OFF',
    validUntil: '2024-12-20',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample6',
    description: 'Valtokenid for beverages only',
    discountType: 'fixed',
    discountAmount: 3.0,
    variant: 'coffee',
  },
  {
    stampId: '7',
    storeName: 'POD 39 HOTEL',
    discount: '10% OFF',
    validUntil: '2024-10-15',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample7',
    description: 'Halloween special - expired',
    discountType: 'percentage',
    discountAmount: 10.0,
    variant: 'hotel',
  },
  {
    stampId: '8',
    storeName: 'Burger Barn',
    discount: '$8 OFF',
    validUntil: '2025-11-30',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample8',
    description: 'Black Frtokeniday deal - already used',
    discountType: 'fixed',
    discountAmount: 8.0,
    variant: 'restaurant',
  },
  {
    stampId: '9',
    storeName: 'Steakhouse NYC',
    discount: '30% OFF',
    validUntil: '2024-09-15',
    status: 'expired',
    ipfs: 'https://ipfs.io/ipfs/QmExample9',
    description: 'Summer special - expired',
    discountType: 'percentage',
    discountAmount: 30,
    variant: 'restaurant',
  },
  {
    stampId: '10',
    storeName: 'Brooklyn Deli',
    discount: '$12 OFF',
    validUntil: '2024-11-20',
    status: 'used',
    ipfs: 'https://ipfs.io/ipfs/QmExample10',
    description: 'Thanksgiving special - used',
    discountType: 'fixed',
    discountAmount: 12.0,
    variant: 'restaurant',
  },
  {
    stampId: '11',
    storeName: 'LEGO STORE',
    discount: '$5 OFF',
    validUntil: '2024-12-25',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample11',
    description: 'Valtokenid for pizzas only',
    discountType: 'fixed',
    discountAmount: 5,
    variant: 'luxury',
  },
  {
    stampId: '12',
    storeName: 'Pizza Palace',
    discount: '$7 OFF',
    validUntil: '2025-12-18',
    status: 'active',
    ipfs: 'https://ipfs.io/ipfs/QmExample12',
    description: 'Weekend special',
    discountType: 'fixed',
    discountAmount: 7.0,
    variant: 'restaurant',
  },
];

export const heroWords = [
  {
    text: 'One',
  },
  {
    text: 'Tap,',
  },
  {
    text: 'One',
  },
  {
    text: 'Stamp.',
    className: 'text-blue-500 dark:text-blue-500',
  },
];
